{% set version = "2.18" %}

package:
  name: graph-tool
  version: {{ version }}

# source:
#   fn: graph-tool-{{ version }}.tar.bz2
#   url: https://downloads.skewed.de/graph-tool/graph-tool-{{ version }}.tar.bz2 
#   md5: 9bec4f9659c8169298831a9acce2742e 

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    # Build tools
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    # ...
    - python
    - numpy
    - scipy
    - boost # ==1.59
    - cairo
    - cairomm
    - pycairo
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - pygobject
    - fontconfig
    - librsvg
    - bzip2
  run:
    - python
    - numpy
    - scipy
    - boost # ==1.59
    - cairo
    - cairomm
    - pycairo
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - fontconfig
    - bzip2
    # Needed for plotting:
    # - librsvg
    # - pygobject 
    # - matplotlib

test:
  imports:
    - graph_tool
    - graph_tool.all

about:
  home: https://graph-tool.skewed.de
  license: GPL
  summary: 'Efficent network analysis with Python.'

