package:
  name: graph-tool
  version: "2.2.35"

build:
  # The build number should be incremented for new builds of the same version
  number: 2       # (defaults to 0)
  
requirements:
  build:
    - python
    - numpy
    - scipy
    - cairo
    - cairomm
    - py2cairo
    - boost
    - cgal
    - sparsehash
    - freetype
    - expat
    
  run:
    - python
    - numpy
    - scipy
    - cairo
    - cairomm
    - py2cairo
    - boost
    - cgal
    - sparsehash
    - freetype
    - expat

about:
  summary: 'Efficient network analysis'
