{% set version = "2.19" %}

package:
  name: graph-tool
  version: {{ version }}

# source:
#  fn: graph-tool-{{ version }}.tar.bz2
#  url: https://downloads.skewed.de/graph-tool/graph-tool-{{ version }}.tar.bz2 
#  sha256: eba1090f94b0434890beedaf0c100dd0fc77e41ebfe29b4725d76cadb82099af 

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    # Build tools
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    # ...
    - python
    - numpy
    - scipy
    - boost # ==1.59
    - cairo
    - cairomm
    - pycairo
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - fontconfig
    - bzip2
    # 
    - librsvg
    - pygobject
  run:
    - python
    - numpy
    - scipy
    - boost # ==1.59
    - cairo
    - cairomm
    - pycairo
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - fontconfig
    - bzip2
    # Needed for plotting:
    # - librsvg
    # - pygobject 
    # - matplotlib

test:
  imports:
    - graph_tool
    - graph_tool.all

about:
  home: https://graph-tool.skewed.de
  license: GPL
  summary: 'Efficent network analysis with Python.'

