package:
  name: graph-tool
  version: "2.14.dev"

source:
  fn: graph-tool-2.14.tar.bz2
  url: https://downloads.skewed.de/graph-tool/graph-tool-2.14.tar.bz2 
  md5: 1f21918bdfee8363424062301b482e1f

build:
  number: 1 
  
requirements:
  build:
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    - gcc
    # ...
    - python
    - numpy
    - scipy
    - boost
#    - boost-python
    - cairo
    - cairomm
    - pycairo
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - pygobject
    - fontconfig
    - librsvg
    - bzip2
  run:
    - libgcc-5
    # ...
    - python
    - numpy
    - scipy
    - boost
#    - boost-python
    - cairo
    - cairomm
    - pycairo
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - pygobject 
    - fontconfig
    - librsvg
    - bzip2

test:
  imports:
    - graph_tool
    - graph_tool.all

about:
  summary: 'Efficient network analysis'
  license: GPL

