package:
  name: graph-tool
  version: 2.2.44

source:
  url: https://downloads.skewed.de/graph-tool/graph-tool-2.2.44.tar.bz2 
  fn: graph-tool-2.2.44.tar.bz2

build:
  number: 5
  
requirements:
  build:
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    - gcc
    - python
    - numpy
    - scipy
    - boost
    - boost-python
    - cairo
    - cairomm
    - py2cairo # [py2k]
    - pycairo # [py3k]
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - pygobject
    - fontconfig
    - librsvg
    - bzip2
  run:
    - python
    - numpy
    - scipy
    - boost
    - boost-python
    - cairo
    - cairomm
    - py2cairo # [py2k]
    - pycairo # [py3k]
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - pygobject 
    - fontconfig
    - librsvg
    - bzip2
about:
  summary: 'Efficient network analysis'
  license: GPL

