{% set version = "2.16" %}

package:
  name: graph-tool
  version: {{ version }}

source:
  fn: graph-tool-{{ version }}.tar.bz2
  url: https://downloads.skewed.de/graph-tool/graph-tool-{{ version }}.tar.bz2 
  md5: c87ba05c20e619e2de933e11abae1591

build:
  number: 0
  skip: True  # [win]
  script_env:
    - TMPDIR
  
requirements:
  build:
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    - gcc
    # ...
    - python
    - numpy
    - scipy
    - boost ==1.59
    - cairo
    - cairomm
    - pycairo
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - pygobject
    - fontconfig
    - librsvg
    - bzip2
  run:
    - libgcc-5
    # ...
    - python
    - numpy
    - scipy
    - boost ==1.59
    - cairo
    - cairomm
    - pycairo
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
    - pygobject 
    - fontconfig
    - librsvg
    - bzip2

test:
  imports:
    - graph_tool
    - graph_tool.all

about:
  summary: 'Efficient network analysis'
  license: GPL
  summary: 'Efficent network analysis with Python.'

