package:
  name: graph-tool
  version: 2.2.44

source:
  url: https://downloads.skewed.de/graph-tool/graph-tool-2.2.44.tar.bz2 
  fn: graph-tool-2.2.44.tar.bz2

build:
  number: 1
  
requirements:
  build:
    - gcc
    - python
    - numpy
    - scipy
    - cairo
    - cairomm
    - py2cairo # [py2k]
    - pycairo # [py3k]
    - boost
    - boost-python
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng
  run:
    - libgcc
    - python
    - numpy
    - scipy
    - cairo
    - cairomm
    - py2cairo # [py2k]
    - pycairo # [py3k]
    - boost
    - boost-python
    - cgal
    - sparsehash
    - freetype
    - expat
    - libpng

about:
  summary: 'Efficient network analysis'
  license: GPL
