package:
    name: boost-python
    version: 1.58.0

source:
   url: http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2
   fn: boost_1_58_0.tar.bz2

build:
    number: 3

requirements:
    build:
      - gcc
      - python
      - bzip2
      - zlib
      - icu 
    run:
      - python
      - bzip2
      - zlib
      - icu

about:
    home: http://www.boost.org/
    license: Boost License
    summary: All Boost libraries except for Boost-Python. Both shared and static libraries are included.
