package:
  name: pygobject
  version: "3.18.2"

source:
  fn: pygobject-3.18.2.tar.xz 
  url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/3.18/pygobject-3.18.2.tar.xz 
  sha256: 2a3cad1517916b74e131e6002c3824361aee0671ffb0d55ded119477fc1c2c5f

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    - python
    - gnome-common
    - glib >=2.43
    - gobject-introspection
    - gettext
    - cairo
    - cairo-gobject
    - pycairo
    - libsigcpp
    - gtk
    - pango
    - libffi
    # Org.X
    #- libxrender
  run:
    - libgcc
    - python
    - gnome-common
    - glib >=2.43
    - gobject-introspection 
    - gettext
    - cairo
    - cairo-gobject
    - pycairo
    - libsigcpp
    - gtk
    - pango
    - libffi
    # Org.X
    #- libxrender

test:
  imports:
    - gi
    - gi.repository
    - gi.repository.GObject
    - gi.repository.GLib
    - gi.repository.Gio
    - gi.repository.Gtk

about:
  home: https://wiki.gnome.org/Projects/PyGObject 
  license: LGPL 2.1
  summary: 'PyGObject is a Python extension module that gives clean and consistent access to the entire GNOME software platform through the use of GObject Introspection.'

