package:
  name: libfaketime
  version: "0.9.6"


source:
  git_url: https://github.com/wolfcw/libfaketime.git


build:
  number: 4

  entry_points:
    - faketime = faketime.__main__:main


requirements:
  build:
    - python

  run:
    - python


test:
  requires: 
    - libfaketime

  commands:
    - faketime '2008-12-24 08:15:42' /bin/date 


about:
  home: https://github.com/wolfcw/libfaketime
  license: GPL
  summary: libfaketime intercepts various system calls which programs use to 
    retrieve the current date and time. It can then report faked dates and times
    (as specified by you, the user) to these programs. This means you can modify
    the system time a program sees without having to change the time system-wide.
