package:
  name: icu
  version: 55.1

build:
  number: 1
 
source:
  url: http://download.icu-project.org/files/icu4c/55.1/icu4c-55_1-src.tgz
  md5: e2d523df79d6cb7855c2fbe284f4db29
  fn: icu4c-55_1-src.tgz

requirements:
  build:
    - gcc
  run:
    - libgcc

about:
    home: http://site.icu-project.org/
    license: MIT
