package:
  name: cairo
  version: "1.14.2"

source:
  url: http://cairographics.org/releases/cairo-1.14.2.tar.xz 
  md5: e1cdfaf1c6c995c4d4c54e07215b0118  
  fn: cairo-1.14.2.tar.xz

build:
  number: 1

requirements:
  build:
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - gcc
    - boost
    - mm-common
    - libsigcpp
    - freetype
    - pixman ==0.32.6
    - libpng
    - zlib
    - glib
    - gobject-introspection
    - fontconfig
  run:
    - boost
    - mm-common
    - libsigcpp
    - freetype
    - pixman ==0.32.6
    - libpng
    - zlib
    - glib
    - gobject-introspection
    - fontconfig

about:
  home: http://cairographics.org/
  license: LGPL
  summary: "Cairo is a 2D graphics library with support for multiple output devices."

