package:
  name: elaspic-meta
  version: "0.1.2"


build:
  number: 1


requirements:
  run:
    # System
    - system
    - readline
    - ncurses
    - openssl

    # Basic python
    - python
    - dateutil
    - python-dateutil
    - pytz

    # Scientific python
    - fastcache
    - numpy
    - scipy
    - pandas
    - psutil
    - scikit-learn >=0.15.0
    - cython
    - biopython

    # Testing
    - pytest
    - nose

    # Documentation
    - docutils
    - sphinx >=1.3
    - sphinxcontrib-programoutput
    - jinja2
    - markupsafe

    # Python 2 / 3 compatibility
    - future
    - six

    # Database access
    - sqlalchemy
    - sqlite
    - mysqlclient
    - psycopg2

    # Binary files
    - stride
    - knot
    - pops
    - msms
    - t_coffee
    - modeller
    - cd-hit
    - provean
    - foldx
    - libfaketime


about:
  home: elaspic.readthedocs.org
  license: GNU General Public License (GPL)
  summary: A metapackage containing all the dependencies for ELASPIC.

