package:
  name: sigcpp
  version: "2.4.0"

source:
  fn: libsigc++-2.4.0.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/libsigc++/2.4/libsigc++-2.4.0.tar.xz

requirements:
  build:
    - gcc
    - mm-common
    - m4
    
  run:
    - libgcc
    - mm-common
    - m4
