package:
  name: autoconf
  version: "dev"

source:
  git_url: git://git.sv.gnu.org/autoconf

build:
  number: 1

requirements:
  build:
    - system
    - gcc
  run:
    - system

about:
  home: http://www.gnu.org/software/autoconf/autoconf.html 
  license: GNU
  summary: Autoconf is an extensible package of M4 macros that produce shell scripts to automatically configure software source code packages. 
