package:
  name: renderproto
  version: 0.11.1

source:
  git_url: http://anongit.freedesktop.org/git/xorg/proto/renderproto.git

requirements:
  build:
    - gcc
    - autoconf
    - automake
    - libtool
    - pkg-config
    - util-macros
    - m4
    - python

  run:
    - libgcc
    - util-macros
    - m4

about:
  home: 'http://cgit.freedesktop.org/xorg/proto/renderproto/'
