package:
  name: libpng
  version: 1.6.18

source:
  url: http://download.sourceforge.net/libpng/libpng-1.6.18.tar.gz 
  fn: libpng-1.6.18.tar.gz

build:
  number: 1

requirements:
  build:
    - system
    - gcc
    - zlib
  run:
    - system
    - zlib

about:
  home: http://www.libpng.org/pub/png/libpng.html 
  license: Open Source
  summary: libpng is the official PNG reference library. 
