package:
  name: rested
  version: "1.1.0"

source:
  git_url: https://github.com/enthought/rested

requirements:
  build:
    - python
    - sphinx
    - traitsui
  run:
    - python
    - sphinx
    - traitsui
    - pyzmq
    - ipython
    - rope
    - pyflakes
    - pygments
    - jinja2
    - pep8
    - pylint
    - pyqt

