package:
  name: mariadb-server
  version: "10.1.13"

source:
  fn: mariadb-10.1.13-linux-x86_64.tar.gz
  url: http://mariadb.mirror.rafal.ca//mariadb-10.1.13/bintar-linux-x86_64/mariadb-10.1.13-linux-x86_64.tar.gz 
  md5: 43615dea64840df3794a25128b93239e 

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    # - gcc
    - cmake
    - bison
    - ncurses
    - zlib
    - lzo
    - jemalloc ==3.6.0
    - aio
    - readline
    - openssl
    - zeromq
    - libxml2
  run:
    - libgcc
    - ncurses ==5.9
    - zlib
    - lzo
    - jemalloc ==3.6.0
    - aio
    - readline
    - openssl
    - zeromq 
    - libxml2

about:
  home: https://mariadb.org/
  license: GPL

